apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  # select pods with label app posts
  selector:
    matchLabels:
      app: posts
  # assign pods label app posts 
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: warrengstar/posts:latest
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000